import { Gender } from '@shitpost-generator/interfaces';
import { users } from './users.constant';

export const names = [
  {
    name: 'Jasmine Gallagher',
    gender: Gender.feminine,
    isEnabled: true,
    tags: ['TTRPG'],
  },
  {
    name: 'Megatron Owen (Meg)',
    gender: Gender.feminine,
    isEnabled: true,
    tags: ['Random'],
    createdBy: users[1],
  },
  {
    name: 'Nadia Bowen',
    gender: Gender.feminine,
    isEnabled: true,
    tags: ['TTRPG'],
    createdBy: users[0],
  },
  {
    name: 'Lee Martinez',
    gender: Gender.androgynous,
    isEnabled: true,
    tags: ['Harry Potter'],
  },
  {
    name: 'Ader Titsoff',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed'],
    createdBy: users[0],
  },
  {
    name: 'Sir Cumference',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed'],
    createdBy: users[0],
  },
  {
    name: 'Harry Azcrac',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed', 'Harry Potter'],
  },
  {
    name: 'Kenny Dewitt',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed'],
    createdBy: users[0],
  },
  {
    name: 'Lou Sirr',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed'],
  },
  {
    name: 'Lou Sirr',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed'],
  },
  {
    name: 'Lou Briccant',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed'],
    createdBy: users[1],
  },
  {
    name: 'Mary Juana',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed'],
  },
  {
    name: 'Nick O’ Teen',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed'],
    createdBy: users[1],
  },
  {
    name: 'Sal Ami',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed', 'Food'],
    createdBy: users[1],
  },
  {
    name: 'Sheeza Freak',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Cursed'],
  },
  {
    name: 'Bill Board',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Random'],
  },
  {
    name: 'Bud Light',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Random', 'Food'],
  },
  {
    name: 'Cara Van',
    gender: Gender.meme,
    isEnabled: true,
    tags: ['Random'],
  },
  {
    name: 'Chris Cross',
    gender: Gender.masculine,
    isEnabled: true,
    tags: ['Random'],
  },
];
